# Generated by Django 4.0.3 on 2022-03-30 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline_flights', to='users.airline'),
        ),
        migrations.AddField(
            model_name='flight',
            name='pax',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flights.pax'),
        ),
        migrations.AddField(
            model_name='flight',
            name='travelers',
            field=models.ManyToManyField(blank=True, related_name='traveler_flights', to=settings.AUTH_USER_MODEL),
        ),
    ]
