# Generated by Django 4.0.3 on 2022-03-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_traveler'),
        ('flights', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='travelers',
            field=models.ManyToManyField(blank=True, related_name='traveler_flights', to='users.traveler'),
        ),
    ]
